config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'courses#index'
  get 'about', to: 'pages#about'
  get 'courses/new', to: 'courses#new'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  resources :projects, only: [:show,:index,:new,:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: {minimum:3, maximum:50}
    validates :short_name, presence: true, length: {minimum:3, maximum:10}
    validates :description, presence: true, length: {minimum:15, maximum:100}
    has_many :student_courses
    has_many :students, through: :student_courses
    has_many :course_projects
    has_many :projects,through: :course_projects
end

app/models/concerns/course_project.rb
class CourseProject < ApplicationRecord
    belongs_to :course
    belongs_to :project
end

app/models/concerns/project.rb
class Project < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum:200}
    has_many :course_projects
    has_many :courses, through: :course_projects

end

app/models/concerns/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase}
    validates :name, presence: true, length: {minimum:3, maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
    validates :email, presence: true, length: { maximum: 105 },            
                uniqueness: { case_sensitive: false },            
                format: { with: VALID_EMAIL_REGEX }
    has_secure_password 
    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/concerns/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student 
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    before_action :require_user

    def current_user
        @current_user ||= Student.find(session[:student_id]) if session[:student_id]
    end 
    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "You must be logged in to perform that action"
            redirect_to login_path
        end

    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user
    def index
        
    end

    def new 

    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    def new

    end 

    def create 
        student = Student.find_by(email: params[:logins][:email].downcase)
        if student && student.authenticate(params[:logins][:password])
            session[:student_id] = student.id
            flash[:notice] = "You Have Successfully logged In"
            redirect_to student 
        else
            flash.now[:notice] = "Something went wrong with your Information"
            render 'new', status: :unprocessable_entity 
        end
    end 

    def destroy 
        session[:student_id] = nil
        flash[:notice] = "You have successfully logged out"
        redirect_to root_path

    end 

end

app/controllers/pages_controller.rb
class PagesController  < ApplicationController
    skip_before_action :require_user
    def about

    end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 
    def new 
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            flash[:notice] = "Project was successfully created"
            redirect_to current_user
        else
            render "new", status: :unprocessable_entity
        end

    end
    
    def index 
        @projects = Project.all

    end
    def show 
        @project = Project.find(params[:id])

    end
    def project_params
        params.require(:project).permit(:name, :description, course_ids: [])
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
    def create
        course_to_add = Course.find(params[:course_id])
        unless current_user.courses.include?(course_to_add)
            StudentCourse.create(course: course_to_add, student: current_user)
            flash[:notice] = "You have succesfully enrolled in #{course_to_add.name}"
            redirect_to current_user
        else
            flash[:notice] = "somnething went wrong with your enrollment"
            redirect_to root_path
        end       
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    before_action :set_student, only: [:show, :edit, :update]
    before_action :require_same_student, only: [:edit, :update]  
    def index 
        @students = Student.all
    
    end

    def show
        
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:success] = "You have successfully signed up"
            redirect_to root_path
        else
            render 'new', status: :unprocessable_entity
        end

    end 

    def edit
       
    end

    def update
        if @student.update(student_params)
            flash[:notice] = "You have successfully updated your profile"
            redirect_to student_path(@student)
        else
            render 'edit', status: :unprocessable_entity 
        end
    end 

    private

    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end
    def set_student
        @student = Student.find(params[:id])
    end
    def require_same_student
        if current_user != @student
            flash[:notice] = "You can edit your own profile"
            redirect_to student_path(current_user)
        end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    def session_link
        if logged_in? 
            link_to "LogOut", logout_path, method: :delete, data: { turbo_method: :delete } 
        else
            link_to "Login", login_path
        end 

    end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">All Courses</h3>
  </div>
</div>

<% Course.all.each_slice(2) do |courses| %>
  <div class="row">
    <% courses.each do |course| %>
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= course.short_name %></span>
            <p class="black-text text-darken-2"><strong><%= course.name %></strong></p>
            <p><%= course.description %></p>
          </div>
          <div class="card-action">
            <% if logged_in? && !(current_user.courses.include?(course)) %>
              <%= button_to "Enroll", course_enroll_path(course_id: course.id), class: "waves-effect waves-light btn-small" %>
            <% end %>
            <%= link_to " View Projects", projects_path %>




          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/courses/new.html.erb
<h1>New</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">About</h5>
      <p class="grey-text text-lighten-4">United International Unuiversity</p>
      <p>demo@gmail.com</p>
      <p>Contact:0191******</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Links</h5>
      <ul>
      <li><%= link_to "Courses", root_path %></li>
      <li><%= link_to "Project", projects_path %></li>

      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
  © 2023 Copyright@uiu
  <a class="grey-text text-lighten-4 right" href="#!">News and Events</a>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>
<!-- Dropdown Structure 
  <ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>-->
  <nav>
    <div class="nav-wrapper">
      <%= link_to "Project Showcase System", root_path, class: "brand-logo" %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">    
        <li><%= link_to "Courses", root_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Semesters", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Students", students_path %></li>
        <li><%= link_to "Profile", student_path(current_user) %></li>
        <% else %>
        <li><%= link_to "SignUp", new_student_path %></li>
        <% end %>
        <!--<li><a class="dropdown-trigger" href="#" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>-->
        
        <li><%= session_link %></li>
      

      </ul>
    </div>
  </nav>
<% flash.each do |key, message| %>
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <div class="card-panel blue accent-3">
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render 'layouts/header'%>

    <main>      
      <div class="container">
      <%= yield %>
      </div>
    </main>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row center">
        <div class="col s12 m12 l12">
            <div class="card-panel">
            <h3 class="header">Log In</h3>
            <div class="row">
                <%= form_for(:logins, html: {class: "col s12"}) do |f| %>
                    <div class="row">
                        <div class="input-field col s12">    
                        <%= f.email_field :email, placeholder: 'Email' , autofocus: true%>
                        <%= f.label :email, class:"active" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">    
                        <%= f.password_field :password, placeholder: 'Enter Password' %>
                        <%= f.label :password, class:"active" %>
                        </div>
                    </div>

                    
                    <div class="row">
                        <div class="input-field col s12"> 
                            <%= f.button '<i class="material-icons right">arrow_forward</i>LogIn'.html_safe , class:"btn waves-effect waves-light "%>
                        </div>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>about</h1>

app/views/projects/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Project</h3>
  </div>
</div>

<% Project.all.each_slice(2) do |projects| %>
  <div class="row">
    <% projects.each do |project| %>
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= project.name %></span>
            <p><%= project.description %></p>
          </div>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<h1 class="text-center mt-4">Create a new Project</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @project %>
      <%= form_with(model: @project, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Project name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <div class="form-group row">
            <%= f.label :description, "Project Description", class: "col-2 col-form-label text-light" %>
        <div class="col-10">
            <%= f.text_field :description, class: "form-control shadow rounded", placeholder: "Enter Description" %>
        </div>
        </div>

        <div class="input-field">
        <%= f.label :course, class:"active"  %>
        <%= f.collection_select(:course_ids, Course.all.all, :id, :name,
          { prompt: "Select Course (can be empty)" }, { multiple: false, class: "browser-default" }) %>
      </div>
      
         

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to projects listing ]', projects_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="container">
    <div class="row center">
    <% if obj.errors.any? %>
        <div class="col s12 m12 l12">
            <div class="card-panel red darken-2">
                <span class="white-text">
                <%= pluralize(obj.errors.count, "error") %>
                prohibited your profile from being saved
                <ul>
                    <% obj.errors.full_messages.each do |message| %> 
                        <li> <%= message %> </li>
                        <% end %>
                </ul>
                
                </span>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj:@student %>
<div class="container">
    <div class="row center">
        <div class="col s12 m12 l12">
            <div class="card-panel">
            <h3 class="header"><%= @student.new_record? ? "SignUp" : "Update Profile" %></h3>
            <div class="row">
                <%= form_for(@student, html: {class: "col s12"}) do |f| %>
                    <div class="row">
                        <div class="input-field col s12">
                        <%= f.text_field :name, autofocus: true, placeholder: 'Name' %>
                        <%= f.label :name, class:"active" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">    
                        <%= f.email_field :email, placeholder: 'Email' %>
                        <%= f.label :email, class:"active" %>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">    
                        <%= f.password_field :password, placeholder: 'Choose Password' %>
                        <%= f.label :password, class:"active" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">    
                        <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %>
                        <%= f.label :password_confirmation, class:"active" %>
                        </div>
                    </div>

                    
                    <div class="row">
                        <div class="input-field col s12"> 
                            <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>SignUp'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit Changes'.html_safe .html_safe , class:"btn waves-effect waves-light ")%>
                        </div>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
<div class="col s12">
<h3 class="center-align">Students Directory</h3>
</div>
</div>

<div class="row">
<% @students.all.each do |student| %>

    <div class="col s6 m6">
    <div class="card blue-grey darken-1">
        <div class="card-content white-text">
        <span class="card-title"><%= student.name %></span>
        <p class="black-text text-darken-2" ><strong><%= student.email %></strong></p>
        <p class="black-text text-darken-2" ><strong>Courses:</strong> None</p>
        
        </div>
        <div class="card-action">
        <%= link_to "View Profile", student_path(student) %>
        </div>
    </div>
    </div>

<% end %>


</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">


    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
            <span class="card-title"><%= @student.name %></span>
            <p class="black-text text-darken-2" ><strong><%= @student.email %></strong></p>
            <br>
            
            <% if current_user == @student %>
                <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student),class:"waves-effect waves-light btn-small" %>
            <% end %>
            <%= link_to '<i class="material-icons right">create</i>Create Project'.html_safe, new_project_path,class:"waves-effect waves-light btn-small" %>
            </div>
            <div class="card-action">
                <p  class="black-text text-darken-2" ><strong>Courses Enrollmrnts:</strong>
                    <%if @student.courses.empty? %>
                    None
                    <% else %>
                    <table class="highlight" >
                    <thead>
                    <tr>
                        <th>Course No</th>
                        <th>Course Title</th>
                    </tr>
                    </thead>

                    <tbody>
                        <% @student.courses.each do |course| %>
                            <tr>
                            <td><%= course.short_name %></td>
                            <td><%= course.name %></td>
                            </tr>
                        <% end %>
                        
                    </tbody>
                    </table>
                    <% end %>

                </p>
            </div>


        </div>
    </div>


</div>